/* eslint-disable @typescript-eslint/no-unused-vars */
/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { Field, ID, ObjectType } from 'type-graphql';
import { Column, JoinColumn, Entity, OneToOne, ManyToOne, OneToMany, PrimaryGeneratedColumn, CreateDateColumn, UpdateDateColumn } from 'typeorm';

import { FacebookUser } from '../../facebook-user/models/FacebookUser';
import { EmailPasswordUser } from '../../email-password-user/models/EmailPasswordUser';
import { File } from '../../file/models/File';
import { UserRole } from '../enums/UserRole';
import * as auth from '../../authorization/auth-checkers';
import { UserCreateInput } from '../inputs/UserCreateInput';
import { UserEditInput } from '../inputs/UserEditInput';
import { UserNestedInput } from '../inputs/UserNestedInput';
import { IRequestContext } from '../../shared/IRequestContext';
import { IAuthorizable } from '../../authorization/IAuthorizable';
import { EntityId, EntityIdScalar } from '../../shared/EntityId';
import { UserAuth } from '../auth/UserAuth';
import { getInputOperationType } from '../../shared/get-input-operation-type';
import { noChange } from '../../shared/no-change';
import { asPromise } from '../../shared/as-promise';

import { updateFacebookUserRelation,updateEmailPasswordUserRelation,updateProfileImageRelation } from './update-operations/user-update-operations';

// <keep-imports>
import {hashPassword, verifyPassword} from '../../authentication/crypto';
// </keep-imports>

// <keep-decorators>
// </keep-decorators>
@Entity()
@ObjectType()
export class User implements IAuthorizable {
  @Field(() => EntityIdScalar)
  @PrimaryGeneratedColumn()
  id: EntityId;

  public authorizationChecker = new UserAuth(this);

  
  @Column({"enum":UserRole,
    // <custom-column-args>
    default: UserRole.USER,
    // </custom-column-args>
  })
  public role: UserRole;

  @Field(() => String, )
  @Column({
    // <custom-column-args>
    // </custom-column-args>
  })
  public name: string;

  @OneToOne(() => FacebookUser, (facebookUser) => facebookUser.user)
  @Field(() => FacebookUser , {"nullable":true})
  public facebookUser: Promise<FacebookUser | undefined | null>;

  @OneToOne(() => EmailPasswordUser, (emailPasswordUser) => emailPasswordUser.user)
  @Field(() => EmailPasswordUser , {"nullable":true})
  public emailPasswordUser: Promise<EmailPasswordUser | undefined | null>;

  @OneToOne(() => File, (file) => file.user)
  @Field(() => File , {"nullable":true})
  public profileImage: Promise<File | undefined | null>;

  @CreateDateColumn()
  @Field()
  createdAt: Date;

  @UpdateDateColumn()
  @Field()
  updatedAt: Date;

  public async update(input: UserCreateInput | UserEditInput | UserNestedInput, context: IRequestContext) {
    const { facebookUser, emailPasswordUser, profileImage, ...data } = input;
    if (noChange(input)) {
      return this;
    }
    if (getInputOperationType(this, input) === 'update') {
      await auth.assertCanUpdate(this, context);
    }
    Object.assign(this, data);

    await updateFacebookUserRelation(this, facebookUser, context);
    await updateEmailPasswordUserRelation(this, emailPasswordUser, context);
    await updateProfileImageRelation(this, profileImage, context);

    context.modelsToSave.push(this);

    // <keep-update-code>
    if (await this.role === undefined) {
      this.role = UserRole.USER;
    }
    // </keep-update-code>
    await auth.assertCanPersist(this, context);

    return this;
  }

  // <keep-methods>
  // </keep-methods>
}
