version: '3'
services:
  ikatun-template:
    container_name: ikatun-template
    image: postgres:10-alpine
    restart: always
    ports:
      - "5402:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ikatun-template
