/* eslint-disable @typescript-eslint/no-unused-vars */
/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { Arg, Args, Mutation, Query, Info, ID, Ctx, Resolver, Root, FieldResolver, Int } from 'type-graphql';
import cleanDeep from 'clean-deep';

import { EmailPasswordUser } from '../models/EmailPasswordUser';
import { EmailPasswordUserCreateInput } from '../inputs/EmailPasswordUserCreateInput';
import { EmailPasswordUserEditInput } from '../inputs/EmailPasswordUserEditInput';
import { EmailPasswordUserSearchInput } from '../inputs/EmailPasswordUserSearchInput';
import { EmailPasswordUserSearchOrderInput } from '../inputs/EmailPasswordUserSearchOrderInput';
import { getFindOptions } from '../../shared/get-find-options';
import { EntityId, EntityIdScalar } from '../../shared/EntityId';
import { IRequestContext } from '../../shared/IRequestContext';
import * as auth from '../../authorization/auth-checkers';
import { PaginatedResponse } from '../../shared/PaginationResponse';
import { resolveGetters } from '../../shared/resolve-getters';

// <keep-imports>
// </keep-imports>

const PaginatedEmailPasswordUserResponse = PaginatedResponse(EmailPasswordUser);

@Resolver(EmailPasswordUser)
export class EmailPasswordUserCrudResolver {
  @Query(() => EmailPasswordUser)
  async emailPasswordUser(@Arg('id', () => EntityIdScalar) id: number, @Info() info, @Ctx() ctx: IRequestContext) {
    return await ctx.em.findOneOrFail(EmailPasswordUser, id, getFindOptions(EmailPasswordUser, info));
  }

  @Query(() => PaginatedEmailPasswordUserResponse)
  public async searchEmailPasswordUsers(
    @Arg('search', () => EmailPasswordUserSearchInput, { nullable: true }) search: EmailPasswordUserSearchInput | null = null,
    @Arg('skip', () => Int, { nullable: true }) skip = 0,
    @Arg('take', () => Int, { nullable: true }) take = 25,
    @Arg('order', () => [EmailPasswordUserSearchOrderInput], { nullable: true }) order: Array<EmailPasswordUserSearchOrderInput> = [],
    @Info() info,
    @Ctx() ctx: IRequestContext,
  ) {
    const defaultFindOptions = getFindOptions(EmailPasswordUser, info, { transformQueryPath: x => x.replace(/^items./, '') });

    const [items, total] = await ctx.em.findAndCount(EmailPasswordUser, cleanDeep({
      ...defaultFindOptions,
      skip,
      take,
      where: resolveGetters(search),
      order: Object.assign({}, ...order),
    }));

    return {
      items,
      total,
      hasMore: skip + take < total,
    };
  }

  @Query(() => [EmailPasswordUser])
  async emailPasswordUsers(@Info() info, @Ctx() ctx: IRequestContext) {
    return await ctx.em.find(EmailPasswordUser, getFindOptions(EmailPasswordUser, info));
  }

  @Mutation(() => EmailPasswordUser)
  async createEmailPasswordUser(@Arg('input') input: EmailPasswordUserCreateInput, @Ctx() ctx: IRequestContext): Promise<EmailPasswordUser> {
    const model = new EmailPasswordUser();
    await model.update(input, ctx);

    await ctx.em.save(ctx.modelsToSave);

    return model;
  }

  @Mutation(() => EmailPasswordUser)
  async updateEmailPasswordUser(@Arg('input') input: EmailPasswordUserEditInput, @Ctx() ctx: IRequestContext) {
    const model = await ctx.em.findOneOrFail(EmailPasswordUser, input.id);
    await model.update(input, ctx);

    // <keep-update-code>
    // </keep-update-code>

    await ctx.em.save(ctx.modelsToSave);

    return model;
  }

  @Mutation(() => Boolean)
  async deleteEmailPasswordUsers(@Arg('ids', () => [ID]) ids: Array<EntityId>, @Ctx() ctx: IRequestContext): Promise<boolean> {
    const entities = await ctx.em.findByIds(EmailPasswordUser, ids);
    await auth.assertCanDelete(entities, ctx);
    await ctx.em.remove(entities);

    return true;
  }

  // <keep-methods>
  // </keep-methods>
}
