/* eslint-disable @typescript-eslint/no-unused-vars */
/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { Field, ID, ObjectType } from 'type-graphql';
import { Column, JoinColumn, Entity, OneToOne, ManyToOne, OneToMany, PrimaryGeneratedColumn, CreateDateColumn, UpdateDateColumn } from 'typeorm';

import { User } from '../../user/models/User';

import * as auth from '../../authorization/auth-checkers';
import { FacebookUserCreateInput } from '../inputs/FacebookUserCreateInput';
import { FacebookUserEditInput } from '../inputs/FacebookUserEditInput';
import { FacebookUserNestedInput } from '../inputs/FacebookUserNestedInput';
import { IRequestContext } from '../../shared/IRequestContext';
import { IAuthorizable } from '../../authorization/IAuthorizable';
import { EntityId, EntityIdScalar } from '../../shared/EntityId';
import { FacebookUserAuth } from '../auth/FacebookUserAuth';
import { getInputOperationType } from '../../shared/get-input-operation-type';
import { noChange } from '../../shared/no-change';
import { asPromise } from '../../shared/as-promise';

import { updateUserRelation } from './update-operations/facebookUser-update-operations';

// <keep-imports>
// </keep-imports>

// <keep-decorators>
// </keep-decorators>
@Entity()
@ObjectType()
export class FacebookUser implements IAuthorizable {
  @Field(() => EntityIdScalar)
  @PrimaryGeneratedColumn()
  id: EntityId;

  public authorizationChecker = new FacebookUserAuth(this);

  @Field(() => String, {"nullable":true})
  @Column({"nullable":true,"type":"text",
    // <custom-column-args>
    unique: true,
    // </custom-column-args>
  })
  public email?: string | null;

  @Field(() => String, )
  @Column({
    // <custom-column-args>
    // </custom-column-args>
  })
  public externalFacebookUserId: string;

  @OneToOne(() => User, (user) => user.facebookUser , {"nullable":false,"onDelete":"CASCADE"})
  @Field(() => User , {"nullable":false})
  @JoinColumn()
  public user: Promise<User>;

  @CreateDateColumn()
  @Field()
  createdAt: Date;

  @UpdateDateColumn()
  @Field()
  updatedAt: Date;

  public async update(input: FacebookUserCreateInput | FacebookUserEditInput | FacebookUserNestedInput, context: IRequestContext) {
    const { user, ...data } = input;
    if (noChange(input)) {
      return this;
    }
    if (getInputOperationType(this, input) === 'update') {
      await auth.assertCanUpdate(this, context);
    }
    Object.assign(this, data);

    await updateUserRelation(this, user, context);

    context.modelsToSave.push(this);

    // <keep-update-code>
    // </keep-update-code>
    await auth.assertCanPersist(this, context);

    return this;
  }

  // <keep-methods>
  // </keep-methods>
}
