/* eslint-disable @typescript-eslint/no-unused-vars */
/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { Field, ID, InputType } from 'type-graphql';

import { EntityId, EntityIdScalar } from '../../shared/EntityId';
import { UserRole } from '../enums/UserRole';
import { FacebookUserNestedInput } from '../../facebook-user/inputs/FacebookUserNestedInput'
import { EmailPasswordUserNestedInput } from '../../email-password-user/inputs/EmailPasswordUserNestedInput'
import { FileNestedInput } from '../../file/inputs/FileNestedInput'

// <keep-imports>
// </keep-imports>

@InputType()
export class UserNestedInput {
  @Field(() => EntityIdScalar, {"nullable":true})
  public id?: EntityId;

  @Field(() => String, {"nullable":true})
  public name?: string | null;

  @Field(() => FacebookUserNestedInput, {"nullable":true})
  public facebookUser?: FacebookUserNestedInput | null;

  @Field(() => EmailPasswordUserNestedInput, {"nullable":true})
  public emailPasswordUser?: EmailPasswordUserNestedInput | null;

  @Field(() => FileNestedInput, {"nullable":true})
  public profileImage?: FileNestedInput | null;

  // <keep-methods>
  // </keep-methods>
}
