/* eslint-disable @typescript-eslint/no-unused-vars */
/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { Arg, Args, Mutation, Query, Info, ID, Ctx, Resolver, Root, FieldResolver, Int } from 'type-graphql';
import cleanDeep from 'clean-deep';

import { FacebookUser } from '../models/FacebookUser';
import { FacebookUserCreateInput } from '../inputs/FacebookUserCreateInput';
import { FacebookUserEditInput } from '../inputs/FacebookUserEditInput';
import { FacebookUserSearchInput } from '../inputs/FacebookUserSearchInput';
import { FacebookUserSearchOrderInput } from '../inputs/FacebookUserSearchOrderInput';
import { getFindOptions } from '../../shared/get-find-options';
import { EntityId, EntityIdScalar } from '../../shared/EntityId';
import { IRequestContext } from '../../shared/IRequestContext';
import * as auth from '../../authorization/auth-checkers';
import { PaginatedResponse } from '../../shared/PaginationResponse';
import { resolveGetters } from '../../shared/resolve-getters';

// <keep-imports>
// </keep-imports>

const PaginatedFacebookUserResponse = PaginatedResponse(FacebookUser);

@Resolver(FacebookUser)
export class FacebookUserCrudResolver {
  @Query(() => FacebookUser)
  async facebookUser(@Arg('id', () => EntityIdScalar) id: number, @Info() info, @Ctx() ctx: IRequestContext) {
    return await ctx.em.findOneOrFail(FacebookUser, id, getFindOptions(FacebookUser, info));
  }

  @Query(() => PaginatedFacebookUserResponse)
  public async searchFacebookUsers(
    @Arg('search', () => FacebookUserSearchInput, { nullable: true }) search: FacebookUserSearchInput | null = null,
    @Arg('skip', () => Int, { nullable: true }) skip = 0,
    @Arg('take', () => Int, { nullable: true }) take = 25,
    @Arg('order', () => [FacebookUserSearchOrderInput], { nullable: true }) order: Array<FacebookUserSearchOrderInput> = [],
    @Info() info,
    @Ctx() ctx: IRequestContext,
  ) {
    const defaultFindOptions = getFindOptions(FacebookUser, info, { transformQueryPath: x => x.replace(/^items./, '') });

    const [items, total] = await ctx.em.findAndCount(FacebookUser, cleanDeep({
      ...defaultFindOptions,
      skip,
      take,
      where: resolveGetters(search),
      order: Object.assign({}, ...order),
    }));

    return {
      items,
      total,
      hasMore: skip + take < total,
    };
  }

  @Query(() => [FacebookUser])
  async facebookUsers(@Info() info, @Ctx() ctx: IRequestContext) {
    return await ctx.em.find(FacebookUser, getFindOptions(FacebookUser, info));
  }

  @Mutation(() => FacebookUser)
  async createFacebookUser(@Arg('input') input: FacebookUserCreateInput, @Ctx() ctx: IRequestContext): Promise<FacebookUser> {
    const model = new FacebookUser();
    await model.update(input, ctx);

    await ctx.em.save(ctx.modelsToSave);

    return model;
  }

  @Mutation(() => FacebookUser)
  async updateFacebookUser(@Arg('input') input: FacebookUserEditInput, @Ctx() ctx: IRequestContext) {
    const model = await ctx.em.findOneOrFail(FacebookUser, input.id);
    await model.update(input, ctx);

    // <keep-update-code>
    // </keep-update-code>

    await ctx.em.save(ctx.modelsToSave);

    return model;
  }

  @Mutation(() => Boolean)
  async deleteFacebookUsers(@Arg('ids', () => [ID]) ids: Array<EntityId>, @Ctx() ctx: IRequestContext): Promise<boolean> {
    const entities = await ctx.em.findByIds(FacebookUser, ids);
    await auth.assertCanDelete(entities, ctx);
    await ctx.em.remove(entities);

    return true;
  }

  // <keep-methods>
  // </keep-methods>
}
